var vehicleWeapons = [
 {
   "ID": "autoCannonLight",
   "Name": "Auto-cannon, Light",
   "Range": "50/100/200",
   "Damage": "2d12",
   "AP": 4,
   "RoF": 4,
   "Shots": 100,
   "Mods": 1,
   "Cost": 50000,
   "Heavy Weapon": true,
   "Reaction Fire": true,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Up to 20mm rounds. A full reload costs $200."
 },
 {
   "ID": "autoCannonMedium",
   "Name": "Auto-cannon, Medium",
   "Range": "50/100/200",
   "Damage": "3d8",
   "AP": 6,
   "RoF": 3,
   "Shots": 100,
   "Mods": 2,
   "Cost": 75000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Covers 21 to 30mm rounds. A full reload costs $400."
 },
 {
   "ID": "autoCannonHeavy",
   "Name": "Auto-cannon, Heavy",
   "Range": "75/150/300",
   "Damage": "4d8",
   "AP": 8,
   "RoF": 3,
   "Shots": 100,
   "Mods": 3,
   "Cost": 200000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Covers 31 to 50mm rounds. A full reload costs $1000."
 },
 {
   "ID": "",
   "Name": "Bombs, Small x12",
   "Range": "Dropped",
   "Damage": "6d10",
   "AP": 10,
   "RoF": 1,
   "Shots": 1,
   "Mods": 1,
   "Cost": 500000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Large blast template. Up to 250 lb. bombs."
 },
 {
   "ID": "",
   "Name": "Bombs, Medium x8",
   "Range": "Dropped",
   "Damage": "8d10",
   "AP": 20,
   "RoF": 1,
   "Shots": 1,
   "Mods": 1,
   "Cost": 1000000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "10\" radius. 251 to 500 lb. bombs."
 },
 {
   "ID": "",
   "Name": "Bombs, Large x4",
   "Range": "Dropped",
   "Damage": "10d10",
   "AP": 30,
   "RoF": 1,
   "Shots": 1,
   "Mods": 1,
   "Cost": 1000000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "20\" radius. 501 to 1000 lb. bombs."
 },
 {
   "ID": "",
   "Name": "Bombs, Block Buster x2",
   "Range": "Dropped",
   "Damage": "10d10",
   "AP": 40,
   "RoF": 1,
   "Shots": 1,
   "Mods": 1,
   "Cost": 1000000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "30” radius. 1001 to 4000 lb. bombs."
 },
 {
   "ID": "",
   "Name": "Bomb, City Buster",
   "Range": "Dropped",
   "Damage": "10d10",
   "AP": 40,
   "RoF": 1,
   "Shots": 1,
   "Mods": 1,
   "Cost": 1000000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "50” radius. 4001 to 8000 lb. bombs."
 },
 {
   "ID": "",
   "Name": "Cannon, Small",
   "Range": "50/100/200",
   "Damage": "3d10",
   "AP": 10,
   "RoF": 1,
   "Shots": 50,
   "Mods": 2,
   "Cost": 400000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Medium blast template. Up to 40mm."
 },
 {
   "ID": "",
   "Name": "Cannon, Small, H.E.",
   "Range": "50/100/200",
   "Damage": "3d8",
   "AP": 5,
   "RoF": 1,
   "Shots": 50,
   "Mods": 2,
   "Cost": 400000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Large blast template. Up to 40mm."
 },
 {
   "ID": "",
   "Name": "Cannon, Medium",
   "Range": "75/150/300",
   "Damage": "4d10",
   "AP": 20,
   "RoF": 1,
   "Shots": 40,
   "Mods": 3,
   "Cost": 600000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Medium blast template. 41mm to 60mm."
 },
 {
   "ID": "",
   "Name": "Cannon, Medium, H.E.",
   "Range": "75/150/300",
   "Damage": "4d8",
   "AP": 10,
   "RoF": 1,
   "Shots": 40,
   "Mods": 3,
   "Cost": 600000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Large blast template. 41mm to 60mm."
 },
 {
   "ID": "",
   "Name": "Cannon, Heavy",
   "Range": "100/200/400",
   "Damage": "5d10",
   "AP": 30,
   "RoF": 1,
   "Shots": 30,
   "Mods": 4,
   "Cost": 800000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Large blast template. 61mm to 80mm."
 },
 {
   "ID": "",
   "Name": "Cannon, Heavy, H.E.",
   "Range": "100/200/400",
   "Damage": "5d8",
   "AP": 15,
   "RoF": 1,
   "Shots": 30,
   "Mods": 4,
   "Cost": 800000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "10\" radius. 61mm to 80mm."
 },
 {
   "ID": "",
   "Name": "Cannon, Super Heavy",
   "Range": "150/300/600",
   "Damage": "6d10",
   "AP": 40,
   "RoF": 1,
   "Shots": 20,
   "Mods": 5,
   "Cost": 1000000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Large blast template. 81mm to 200mm"
 },
 {
   "ID": "",
   "Name": "Cannon, Super Heavy, H.E.",
   "Range": "150/300/600",
   "Damage": "6d8",
   "AP": 20,
   "RoF": 1,
   "Shots": 20,
   "Mods": 5,
   "Cost": 1000000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "10\" radius. 81mm to 200mm"
 },
 {
   "ID": "",
   "Name": "Flamethrower, Heavy",
   "Range": "See notes",
   "Damage": "3d12",
   "AP": 0,
   "RoF": 1,
   "Shots": 30,
   "Mods": 2,
   "Cost": 1000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Targets may catch fire. Can be fired in a Cone Template or a Medium Burst Template up to 18” distant. Affects target’s least Armored area."
 },
 {
   "ID": "",
   "Name": "Grenade Launcer",
   "Range": "24/48/96",
   "Damage": "3d6",
   "AP": 0,
   "RoF": 3,
   "Shots": 20,
   "Mods": 1,
   "Cost": 700,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Grenades cost $50 and weigh .25 pounds each. They are the same as the grenades listed on page 20 and may be thrown as well."
 },
 {
   "ID": "",
   "Name": "Laser, Light",
   "Range": "150/300/600",
   "Damage": "2d10",
   "AP": 5,
   "RoF": 1,
   "Shots": 100,
   "Mods": 1,
   "Cost": 100000,
   "Heavy Weapon": true,
   "Reaction Fire": true,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "-"
 },
 {
   "ID": "",
   "Name": "Laser, Medium",
   "Range": "150/300/600",
   "Damage": "3d10",
   "AP": 10,
   "RoF": 1,
   "Shots": 100,
   "Mods": 2,
   "Cost": 500000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "-"
 },
 {
   "ID": "",
   "Name": "Laser, Heavy",
   "Range": "150/300/600",
   "Damage": "4d10",
   "AP": 15,
   "RoF": 1,
   "Shots": 100,
   "Mods": 3,
   "Cost": 1000000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "-"
 },
 {
   "ID": "",
   "Name": "Laser, Super Heavy",
   "Range": "150/300/600",
   "Damage": "6d10",
   "AP": 25,
   "RoF": 1,
   "Shots": 100,
   "Mods": 5,
   "Cost": 2000000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "-"
 },
 {
   "ID": "",
   "Name": "Laser, Massive",
   "Range": "150/300/600",
   "Damage": "8d10",
   "AP": 40,
   "RoF": 1,
   "Shots": 100,
   "Mods": 7,
   "Cost": 4000000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Size 14 and Larger ships, vehicles, or walkers only."
 },
 {
   "ID": "",
   "Name": "Laser, Mega",
   "Range": "150/300/600",
   "Damage": "10d10",
   "AP": 50,
   "RoF": 0.5,
   "Shots": 100,
   "Mods": 10,
   "Cost": 10000000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Size 16 and Larger ships, vehicles, or walkers only."
 },
 {
   "ID": "",
   "Name": "Mass Driver 3",
   "Range": "100/200/400",
   "Damage": "3d12",
   "AP": 0,
   "RoF": 1,
   "Shots": 15,
   "Mods": 1.5,
   "Cost": 300000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Projectiles are 10 lb per level and cost $100 per level each. Effective Range is tripled in space."
 },
 {
   "ID": "",
   "Name": "Mass Driver 4",
   "Range": "100/200/400",
   "Damage": "4d12",
   "AP": 0,
   "RoF": 1,
   "Shots": 15,
   "Mods": 2,
   "Cost": 400000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Projectiles are 10 lb per level and cost $100 per level each. Effective Range is tripled in space."
 },
 {
   "ID": "",
   "Name": "Mass Driver 6",
   "Range": "100/200/400",
   "Damage": "6d12",
   "AP": 0,
   "RoF": 1,
   "Shots": 15,
   "Mods": 3,
   "Cost": 600000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Projectiles are 10 lb per level and cost $100 per level each. Effective Range is tripled in space."
 },
 {
   "ID": "",
   "Name": "Mass Driver 8",
   "Range": "100/200/400",
   "Damage": "8d12",
   "AP": 0,
   "RoF": 1,
   "Shots": 15,
   "Mods": 4,
   "Cost": 800000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Projectiles are 10 lb per level and cost $100 per level each. Effective Range is tripled in space."
 },
 {
   "ID": "",
   "Name": "Mass Driver 10",
   "Range": "100/200/400",
   "Damage": "10d12",
   "AP": 0,
   "RoF": 1,
   "Shots": 15,
   "Mods": 5,
   "Cost": 1000000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Projectiles are 10 lb per level and cost $100 per level each. Effective Range is tripled in space."
 },
 {
   "ID": "",
   "Name": "Mass Driver 12",
   "Range": "100/200/400",
   "Damage": "12d12",
   "AP": 0,
   "RoF": 1,
   "Shots": 15,
   "Mods": 6,
   "Cost": 1200000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Projectiles are 10 lb per level and cost $100 per level each. Effective Range is tripled in space."
 },
 {
   "ID": "",
   "Name": "Mass Driver 14",
   "Range": "100/200/400",
   "Damage": "14d12",
   "AP": 0,
   "RoF": 1,
   "Shots": 15,
   "Mods": 7,
   "Cost": 1400000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Projectiles are 10 lb per level and cost $100 per level each. Effective Range is tripled in space."
 },
 {
   "ID": "",
   "Name": "Mass Driver 16",
   "Range": "100/200/400",
   "Damage": "16d12",
   "AP": 0,
   "RoF": 1,
   "Shots": 15,
   "Mods": 8,
   "Cost": 1600000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Projectiles are 10 lb per level and cost $100 per level each. Effective Range is tripled in space."
 },
 {
   "ID": "",
   "Name": "Mass Driver 20",
   "Range": "100/200/400",
   "Damage": "20d12",
   "AP": 0,
   "RoF": 1,
   "Shots": 15,
   "Mods": 10,
   "Cost": 2000000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Projectiles are 10 lb per level and cost $100 per level each. Effective Range is tripled in space."
 },
 {
   "ID": "",
   "Name": "Missile, Light x12",
   "Range": "200/400/800",
   "Damage": "6d6",
   "AP": 8,
   "RoF": 1,
   "Shots": 1,
   "Mods": 1,
   "Cost": 150000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Small blast template."
 },
 {
   "ID": "",
   "Name": "Missile, Heavy/AT x8",
   "Range": "200/400/800",
   "Damage": "8d6",
   "AP": 15,
   "RoF": 1,
   "Shots": 1,
   "Mods": 1,
   "Cost": 200000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Medium blast template."
 },
 {
   "ID": "",
   "Name": "Missile, Anti-Tank x8",
   "Range": "100/200/400",
   "Damage": "6d6",
   "AP": 20,
   "RoF": 1,
   "Shots": 1,
   "Mods": 1,
   "Cost": 400000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Medium blast template."
 },
 {
   "ID": "",
   "Name": "Torpedo, Light",
   "Range": "300/600/1200",
   "Damage": "8d12",
   "AP": 40,
   "RoF": 1,
   "Shots": 1,
   "Mods": 1,
   "Cost": 1000000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Large blast template. Space or watercraft only. Half Range in water."
 },
 {
   "ID": "",
   "Name": "Torpedo, Heavy",
   "Range": "300/600/1200",
   "Damage": "10d12",
   "AP": 80,
   "RoF": 1,
   "Shots": 1,
   "Mods": 1,
   "Cost": 1000000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "Large blast template. Space or watercraft only. Half Range in water."
 },
 {
   "ID": "",
   "Name": "Medium MG",
   "Range": "30/60/120",
   "Damage": "2d8+1",
   "AP": 2,
   "RoF": 4,
   "Shots": 200,
   "Mods": 0.5,
   "Cost": 3000,
   "Heavy Weapon": false,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "A 200 round belt of ammo costs $400 and weighs 15 pounds."
 },
 {
   "ID": "",
   "Name": "Heavy MG",
   "Range": "50/100/200",
   "Damage": "2d10",
   "AP": 4,
   "RoF": 3,
   "Shots": 200,
   "Mods": 0.5,
   "Cost": 5000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "A 200 round belt of ammo costs $250 and weighs 15 pounds."
 },
 {
   "ID": "",
   "Name": "Minigun",
   "Range": "24/48/96",
   "Damage": "2d8+4",
   "AP": 3,
   "RoF": 4,
   "Shots": 1000,
   "Mods": 1,
   "Cost": 10000,
   "Heavy Weapon": true,
   "Reaction Fire": false,
   "Dual Linked": false,
   "Quad Linked": false,
   "Notes": "An additional 1000 round drum of ammunition weighs 20 pounds and costs $1000."
 }
];